apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: backend-app
  namespace: argocd
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  destination:
    server: https://kubernetes.default.svc
    namespace: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true  # default ns usually exists, but include just in case
  source:
    helm:
      releaseName: backend
    repoURL: https://github.com/Y2not2nd/Security-Focused-AKS-Deployment-Kubernets
    targetRevision: main
    path: helm-charts/backend 