apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: istio-base-app
  namespace: argocd
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  destination:
    server: https://kubernetes.default.svc
    namespace: istio-system
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true
  source:
    helm:
      releaseName: istio-base
    repoURL: https://istio-release.storage.googleapis.com/charts
    targetRevision: 1.22.8  # Istio chart version (matching Istio 1.22.x)
    chart: base 