apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: istio-config-app
  namespace: argocd
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  destination:
    server: https://kubernetes.default.svc
    namespace: istio-system
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
  source:
    repoURL: https://github.com/Y2not2nd/aks-Deployment-Kubernets-SecurityFocused
    targetRevision: main
    path: istio-config 