apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: mongodb-app
  namespace: argocd
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  destination:
    server: https://kubernetes.default.svc
    namespace: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
  source:
    repoURL: https://github.com/Y2not2nd/Security-Focused-AKS-Deployment-Kubernets
    targetRevision: main
    path: helm-charts/mongodb
    helm:
      releaseName: mongodb

