apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: mongodb-app
  namespace: argocd
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  destination:
    server: https://kubernetes.default.svc
    namespace: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
  source:
    helm:
      releaseName: mongodb
      values: |
        architecture: standalone
        auth:
          enabled: true
          username: appuser
          password: appPass123
          database: mydb
        fullnameOverride: mongodb
        metrics:
          enabled: true
    repoURL: https://charts.bitnami.com/bitnami
    targetRevision: 13.6.4
    chart: mongodb 