apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: vault-app
  namespace: argocd
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  destination:
    server: https://kubernetes.default.svc
    namespace: vault
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true
  source:
    helm:
      releaseName: vault
      values: |
        injector:
          enabled: true
        server:
          dev:
            enabled: true
          ui:
            enabled: true
    repoURL: https://helm.releases.hashicorp.com
    targetRevision: 0.30.0  # Helm chart version for Vault
    chart: vault 