apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
  namespace: default
  labels:
    app: backend
  annotations:
    argocd.argoproj.io/tracking-id: backend-app:apps/Deployment:default/backend
spec:
  replicas: 2
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: backend
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
  template:
    metadata:
      labels:
        app: backend
      annotations:
        sidecar.istio.io/inject: "true"
        vault.hashicorp.com/agent-inject: "true"
        vault.hashicorp.com/agent-inject-secret-db-creds.txt: secret/data/db-creds
        vault.hashicorp.com/agent-inject-template-db-creds.txt: |
          {{- with secret "secret/db-creds" -}}
          {{ .Data.data.uri }}
          {{- end }}
        vault.hashicorp.com/role: backend-role
    spec:
      containers:
        - name: backend
          image: akssecuredemoacr.azurecr.io/backend-app:v1
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8080
              protocol: TCP
          resources:
            limits:
              cpu: 500m
              memory: 256Mi
            requests:
              cpu: 200m
              memory: 128Mi
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      terminationGracePeriodSeconds: 30
      securityContext: {}
      schedulerName: default-scheduler
