replicaCount: 2

image:
  repository: akssecuredemoacr.azurecr.io/backend-app
  tag: "v3"
  pullPolicy: IfNotPresent

imagePullSecrets: []

service:
  type: ClusterIP
  port: 8080

resources:
  limits:
    cpu: 500m
    memory: 256Mi
  requests:
    cpu: 200m
    memory: 128Mi

hpa:
  enabled: true
  maxReplicas: 5
  cpuTargetPercentage: 50

env:
  mongoUri: "mongodb://root:3Agc82DUHf@mongodb:27017/mydb?authSource=admin"

podAnnotations:
  sidecar.istio.io/inject: "true"

serviceAccountName: default
