replicaCount: 2

image:
  repository: akssecuredemoacr.azurecr.io/backend-app
  tag: "v3"
  pullPolicy: IfNotPresent

service:
  type: ClusterIP
  port: 8080

resources:
  limits:
    cpu: 500m
    memory: 256Mi
  requests:
    cpu: 200m
    memory: 128Mi

hpa:
  enabled: true
  minReplicas: 1
  maxReplicas: 5
  cpuTargetPercentage: 50

env:
  - name: MONGO_URI
    valueFrom:
      secretKeyRef:
        name: mongodb-credentials
        key: connectionString
