{{- if .Values.auth.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: mongodb-credentials
  labels:
{{ include "mongodb.labels" . | indent 4 }}
type: Opaque
stringData:
  username: {{ .Values.auth.rootUsername | quote }}
  password: {{ .Values.auth.rootPassword | quote }}
  database: {{ .Values.auth.database | quote }}
  connectionString: {{ printf "mongodb://%s:%s@%s.%s.svc.cluster.local:%d/%s?authSource=admin" .Values.auth.rootUsername .Values.auth.rootPassword (include "mongodb.fullname" .) .Release.Namespace (int .Values.service.port) .Values.auth.database | quote }}
{{- end }}
