apiVersion: v1
kind: Service
metadata:
  name: {{ include "mongodb.fullname" . }}
  labels:
{{ include "mongodb.labels" . | indent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - name: mongodb
      port: {{ .Values.service.port }}
      targetPort: 27017
      protocol: TCP
  selector:
    app: mongodb
---
{{- if .Values.metrics.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "mongodb.fullname" . }}-metrics
  labels:
{{ include "mongodb.labels" . | indent 4 }}
    component: metrics
spec:
  type: ClusterIP
  ports:
    - name: metrics
      port: {{ .Values.metrics.port }}
      targetPort: {{ .Values.metrics.port }}
      protocol: TCP
  selector:
    app: mongodb
{{- end }}
